//! this file is used to bridge C types like enums and error codes to be a proper zig types
pub const CurlOpt = enum(c_int) {
    writedata = 10001,
    url = 10002,
    port = 3,
    proxy = 10004,
    userpwd = 10005,
    proxyuserpwd = 10006,
    range = 10007,
    readdata = 10009,
    errorbuffer = 10010,
    writefunction = 20011,
    readfunction = 20012,
    timeout = 13,
    infilesize = 14,
    postfields = 10015,
    referer = 10016,
    ftpport = 10017,
    useragent = 10018,
    low_speed_limit = 19,
    low_speed_time = 20,
    resume_from = 21,
    cookie = 10022,
    httpheader = 10023,
    httppost = 10024,
    sslcert = 10025,
    keypasswd = 10026,
    crlf = 27,
    quote = 10028,
    headerdata = 10029,
    cookiefile = 10031,
    sslversion = 32,
    timecondition = 33,
    timevalue = 34,
    customrequest = 10036,
    stderr = 10037,
    postquote = 10039,
    verbose = 41,
    header = 42,
    noprogress = 43,
    nobody = 44,
    failonerror = 45,
    upload = 46,
    post = 47,
    dirlistonly = 48,
    append = 50,
    netrc = 51,
    followlocation = 52,
    transfertext = 53,
    put = 54,
    progressfunction = 20056,
    xferinfodata = 10057,
    autoreferer = 58,
    proxyport = 59,
    postfieldsize = 60,
    httpproxytunnel = 61,
    interface = 10062,
    krblevel = 10063,
    ssl_verifypeer = 64,
    cainfo = 10065,
    maxredirs = 68,
    filetime = 69,
    telnetoptions = 10070,
    maxconnects = 71,
    fresh_connect = 74,
    forbid_reuse = 75,
    random_file = 10076,
    egdsocket = 10077,
    connecttimeout = 78,
    headerfunction = 20079,
    httpget = 80,
    ssl_verifyhost = 81,
    cookiejar = 10082,
    ssl_cipher_list = 10083,
    http_version = 84,
    ftp_use_epsv = 85,
    sslcerttype = 10086,
    sslkey = 10087,
    sslkeytype = 10088,
    sslengine = 10089,
    sslengine_default = 90,
    dns_use_global_cache = 91,
    dns_cache_timeout = 92,
    prequote = 10093,
    debugfunction = 20094,
    debugdata = 10095,
    cookiesession = 96,
    capath = 10097,
    buffersize = 98,
    nosignal = 99,
    share = 10100,
    proxytype = 101,
    accept_encoding = 10102,
    private = 10103,
    http200aliases = 10104,
    unrestricted_auth = 105,
    ftp_use_eprt = 106,
    httpauth = 107,
    ssl_ctx_function = 20108,
    ssl_ctx_data = 10109,
    ftp_create_missing_dirs = 110,
    proxyauth = 111,
    server_response_timeout = 112,
    ipresolve = 113,
    maxfilesize = 114,
    infilesize_large = 30115,
    resume_from_large = 30116,
    maxfilesize_large = 30117,
    netrc_file = 10118,
    use_ssl = 119,
    postfieldsize_large = 30120,
    tcp_nodelay = 121,
    ftpsslauth = 129,
    ioctlfunction = 20130,
    ioctldata = 10131,
    ftp_account = 10134,
    cookielist = 10135,
    ignore_content_length = 136,
    ftp_skip_pasv_ip = 137,
    ftp_filemethod = 138,
    localport = 139,
    localportrange = 140,
    connect_only = 141,
    conv_from_network_function = 20142,
    conv_to_network_function = 20143,
    conv_from_utf8_function = 20144,
    max_send_speed_large = 30145,
    max_recv_speed_large = 30146,
    ftp_alternative_to_user = 10147,
    sockoptfunction = 20148,
    sockoptdata = 10149,
    ssl_sessionid_cache = 150,
    ssh_auth_types = 151,
    ssh_public_keyfile = 10152,
    ssh_private_keyfile = 10153,
    ftp_ssl_ccc = 154,
    timeout_ms = 155,
    connecttimeout_ms = 156,
    http_transfer_decoding = 157,
    http_content_decoding = 158,
    new_file_perms = 159,
    new_directory_perms = 160,
    postredir = 161,
    ssh_host_public_key_md5 = 10162,
    opensocketfunction = 20163,
    opensocketdata = 10164,
    copypostfields = 10165,
    proxy_transfer_mode = 166,
    seekfunction = 20167,
    seekdata = 10168,
    crlfile = 10169,
    issuercert = 10170,
    address_scope = 171,
    certinfo = 172,
    username = 10173,
    password = 10174,
    proxyusername = 10175,
    proxypassword = 10176,
    noproxy = 10177,
    tftp_blksize = 178,
    socks5_gssapi_service = 10179,
    socks5_gssapi_nec = 180,
    protocols = 181,
    redir_protocols = 182,
    ssh_knownhosts = 10183,
    ssh_keyfunction = 20184,
    ssh_keydata = 10185,
    mail_from = 10186,
    mail_rcpt = 10187,
    ftp_use_pret = 188,
    rtsp_request = 189,
    rtsp_session_id = 10190,
    rtsp_stream_uri = 10191,
    rtsp_transport = 10192,
    rtsp_client_cseq = 193,
    rtsp_server_cseq = 194,
    interleavedata = 10195,
    interleavefunction = 20196,
    wildcardmatch = 197,
    chunk_bgn_function = 20198,
    chunk_end_function = 20199,
    fnmatch_function = 20200,
    chunk_data = 10201,
    fnmatch_data = 10202,
    resolve = 10203,
    tlsauth_username = 10204,
    tlsauth_password = 10205,
    tlsauth_type = 10206,
    transfer_encoding = 207,
    closesocketfunction = 20208,
    closesocketdata = 10209,
    gssapi_delegation = 210,
    dns_servers = 10211,
    accepttimeout_ms = 212,
    tcp_keepalive = 213,
    tcp_keepidle = 214,
    tcp_keepintvl = 215,
    ssl_options = 216,
    mail_auth = 10217,
    sasl_ir = 218,
    xferinfofunction = 20219,
    xoauth2_bearer = 10220,
    dns_interface = 10221,
    dns_local_ip4 = 10222,
    dns_local_ip6 = 10223,
    login_options = 10224,
    ssl_enable_npn = 225,
    ssl_enable_alpn = 226,
    expect_100_timeout_ms = 227,
    proxyheader = 10228,
    headeropt = 229,
    pinnedpublickey = 10230,
    unix_socket_path = 10231,
    ssl_verifystatus = 232,
    ssl_falsestart = 233,
    path_as_is = 234,
    proxy_service_name = 10235,
    service_name = 10236,
    pipewait = 237,
    default_protocol = 10238,
    stream_weight = 239,
    stream_depends = 10040,
    stream_depends_e = 10040,
    tftp_no_options = 242,
    connect_to = 10243,
    tcp_fastopen = 244,
    keep_sending_on_error = 245,
    proxy_cainfo = 10246,
    proxy_capath = 10247,
    proxy_ssl_verifypeer = 248,
    proxy_ssl_verifyhost = 249,
    proxy_sslversion = 250,
    proxy_tlsauth_username = 10251,
    proxy_tlsauth_password = 10252,
    proxy_tlsauth_type = 10253,
    proxy_sslcert = 10254,
    proxy_sslcerttype = 10255,
    proxy_sslkey = 10256,
    proxy_sslkeytype = 10257,
    proxy_keypasswd = 10258,
    proxy_ssl_cipher_list = 10259,
    proxy_crlfile = 10260,
    proxy_ssl_options = 261,
    pre_proxy = 10262,
    proxy_pinnedpublickey = 10263,
    abstract_unix_socket = 10264,
    suppress_connect_headers = 265,
    request_target = 10266,
    socks5_auth = 267,
    ssh_compression = 268,
    mimepost = 10269,
    timevalue_large = 30270,
    happy_eyeballs_timeout_ms = 271,
    resolver_start_function = 20272,
    resolver_start_data = 10273,
    haproxyprotocol = 274,
    dns_shuffle_addresses = 275,
    tls13_ciphers = 10276,
    proxy_tls13_ciphers = 10277,
    disallow_username_in_url = 278,
    doh_url = 10279,
    upload_buffersize = 280,
    upkeep_interval_ms = 281,
    curlu = 10282,
    trailerfunction = 20283,
    trailerdata = 10284,
    http09_allowed = 285,
    altsvc_ctrl = 286,
    altsvc = 10287,
    maxage_conn = 288,
    sasl_authzid = 10289,
    mail_rcpt_allowfails = 290,
    sslcert_blob = 40291,
    sslkey_blob = 40292,
    proxy_sslcert_blob = 40293,
    proxy_sslkey_blob = 40294,
    issuercert_blob = 40295,
    proxy_issuercert = 10296,
    proxy_issuercert_blob = 40297,
    ssl_ec_curves = 10298,
    hsts_ctrl = 299,
    hsts = 10300,
    hstsreadfunction = 20301,
    hstsreaddata = 10302,
    hstswritefunction = 20303,
    hstswritedata = 10304,
    aws_sigv4 = 10305,
    doh_ssl_verifypeer = 306,
    doh_ssl_verifyhost = 307,
    doh_ssl_verifystatus = 308,
    cainfo_blob = 40309,
    proxy_cainfo_blob = 40310,
    ssh_host_public_key_sha256 = 10311,
    prereqfunction = 20312,
    prereqdata = 10313,
    maxlifetime_conn = 314,
    mime_options = 315,
    ssh_hostkeyfunction = 20316,
    ssh_hostkeydata = 10317,
    protocols_str = 10318,
    redir_protocols_str = 10319,
    ws_options = 320,
    ca_cache_timeout = 321,
    quick_exit = 322,
    haproxy_client_ip = 10323,
    server_response_timeout_ms = 324,
    ech = 10325,
    tcp_keepcnt = 326,
    upload_flags = 327,
    ssl_signature_algorithms = 10328,
    httpsig_algorithm = 329,
    httpsig_key = 10330,
    httpsig_keyid = 10331,
    httpsig_headers = 10332,
    lastentry = 10333,
    encoding = 10102,
    file = 10001,
    infile = 10009,
    writeheader = 10029,
    // CURLOPTTYPE_LONG = 0,
    // CURLOPTTYPE_OBJECTPOINT = 10000,
    // CURLOPTTYPE_FUNCTIONPOINT = 20000,
    // CURLOPTTYPE_OFF_T = 30000,
    // CURLOPTTYPE_BLOB = __helpers.promoteIntLiteral(c_int, 40000, .decimal),
    // CURLOPTTYPE_STRINGPOINT = CURLOPTTYPE_OBJECTPOINT,
    // CURLOPTTYPE_SLISTPOINT = CURLOPTTYPE_OBJECTPOINT,
    // CURLOPTTYPE_CBPOINT = CURLOPTTYPE_OBJECTPOINT,
    // CURLOPTTYPE_VALUES = CURLOPTTYPE_LONG,
    progressdata = 10057,
    post301 = 161,
    sslkeypasswd = 10026,
    ftpappend = 50,
    ftplistonly = 48,
    ftp_ssl = 119,
    sslcertpasswd = 10026,
    rtspheader = 10023,
};

/// CURLE wrapper containing enum and error and a functions to return Error from enum value
pub const CurlCode = struct {
    /// NOTE: there are still some that non error here cleanup later
    pub const CurlError = error{
        UnsupportedProtocol,
        FailedInit,
        UrlMalformat,
        NotBuiltIn,
        CouldntResolveProxy,
        CouldntResolveHost,
        CouldntConnect,
        WeirdServerReply,
        RemoteAccessDenied,
        FtpAcceptFailed,
        FtpWeirdPassReply,
        FtpAcceptTimeout,
        FtpWeirdPasvReply,
        FtpWeird227Format,
        FtpCantGetHost,
        Http2,
        FtpCouldntSetType,
        PartialFile,
        FtpCouldntRetrFile,
        Obsolete20,
        QuoteError,
        HttpReturnedError,
        WriteError,
        Obsolete24,
        UploadFailed,
        ReadError,
        OutOfMemory,
        OperationTimedout,
        Obsolete29,
        FtpPortFailed,
        FtpCouldntUseRest,
        Obsolete32,
        RangeError,
        Obsolete34,
        SslConnectError,
        BadDownloadResume,
        FileCouldntReadFile,
        LdapCannotBind,
        LdapSearchFailed,
        Obsolete40,
        Obsolete41,
        AbortedByCallback,
        BadFunctionArgument,
        Obsolete44,
        InterfaceFailed,
        Obsolete46,
        TooManyRedirects,
        UnknownOption,
        SetoptOptionSyntax,
        Obsolete50,
        Obsolete51,
        GotNothing,
        SslEngineNotfound,
        SslEngineSetfailed,
        SendError,
        RecvError,
        Obsolete57,
        SslCertproblem,
        SslCipher,
        PeerFailedVerification,
        BadContentEncoding,
        Obsolete62,
        FilesizeExceeded,
        UseSslFailed,
        SendFailRewind,
        SslEngineInitfailed,
        LoginDenied,
        TftpNotfound,
        TftpPerm,
        RemoteDiskFull,
        TftpIllegal,
        TftpUnknownid,
        RemoteFileExists,
        TftpNosuchuser,
        Obsolete75,
        Obsolete76,
        SslCacertBadfile,
        RemoteFileNotFound,
        Ssh,
        SslShutdownFailed,
        Again,
        SslCrlBadfile,
        SslIssuerError,
        FtpPretFailed,
        RtspCseqError,
        RtspSessionError,
        FtpBadFileList,
        ChunkFailed,
        NoConnectionAvailable,
        SslPinnedpubkeynotmatch,
        SslInvalidcertstatus,
        Http2Stream,
        RecursiveApiCall,
        AuthError,
        Http3,
        QuicConnectError,
        Proxy,
        SslClientcert,
        UnrecoverablePoll,
        TooLarge,
        EchRequired,
    };

    const CurlCodeEnum = enum {
        ok,
        unsupported_protocol,
        failed_init,
        url_malformat,
        not_built_in,
        couldnt_resolve_proxy,
        couldnt_resolve_host,
        couldnt_connect,
        weird_server_reply,
        remote_access_denied,
        ftp_accept_failed,
        ftp_weird_pass_reply,
        ftp_accept_timeout,
        ftp_weird_pasv_reply,
        ftp_weird_227_format,
        ftp_cant_get_host,
        http2,
        ftp_couldnt_set_type,
        partial_file,
        ftp_couldnt_retr_file,
        obsolete20,
        quote_error,
        http_returned_error,
        write_error,
        obsolete24,
        upload_failed,
        read_error,
        out_of_memory,
        operation_timedout,
        obsolete29,
        ftp_port_failed,
        ftp_couldnt_use_rest,
        obsolete32,
        range_error,
        obsolete34,
        ssl_connect_error,
        bad_download_resume,
        file_couldnt_read_file,
        ldap_cannot_bind,
        ldap_search_failed,
        obsolete40,
        obsolete41,
        aborted_by_callback,
        bad_function_argument,
        obsolete44,
        interface_failed,
        obsolete46,
        too_many_redirects,
        unknown_option,
        setopt_option_syntax,
        obsolete50,
        obsolete51,
        got_nothing,
        ssl_engine_notfound,
        ssl_engine_setfailed,
        send_error,
        recv_error,
        obsolete57,
        ssl_certproblem,
        ssl_cipher,
        peer_failed_verification,
        bad_content_encoding,
        obsolete62,
        filesize_exceeded,
        use_ssl_failed,
        send_fail_rewind,
        ssl_engine_initfailed,
        login_denied,
        tftp_notfound,
        tftp_perm,
        remote_disk_full,
        tftp_illegal,
        tftp_unknownid,
        remote_file_exists,
        tftp_nosuchuser,
        obsolete75,
        obsolete76,
        ssl_cacert_badfile,
        remote_file_not_found,
        ssh,
        ssl_shutdown_failed,
        again,
        ssl_crl_badfile,
        ssl_issuer_error,
        ftp_pret_failed,
        rtsp_cseq_error,
        rtsp_session_error,
        ftp_bad_file_list,
        chunk_failed,
        no_connection_available,
        ssl_pinnedpubkeynotmatch,
        ssl_invalidcertstatus,
        http2_stream,
        recursive_api_call,
        auth_error,
        http3,
        quic_connect_error,
        proxy,
        ssl_clientcert,
        unrecoverable_poll,
        too_large0,
        ech_required1,
        // FUNCTION_NOT_FOUNDRLE_OBSOLETE41,
        // HTTP_POST_ERRORRLE_OBSOLETE34,
        // OBSOLETE16RLE_HTTP2,
        // OBSOLETE10RLE_FTP_ACCEPT_FAILED,
        // OBSOLETE12RLE_FTP_ACCEPT_TIMEOUT,
        // FTP_WEIRD_SERVER_REPLYRLE_WEIRD_SERVER_REPLY,
        // SSL_CACERTRLE_PEER_FAILED_VERIFICATION,
        // UNKNOWN_TELNET_OPTIONRLE_UNKNOWN_OPTION,
        // TELNET_OPTION_SYNTAXRLE_SETOPT_OPTION_SYNTAX,
        // SSL_PEER_CERTIFICATERLE_PEER_FAILED_VERIFICATION,
        // OBSOLETERLE_OBSOLETE50,
        // BAD_PASSWORD_ENTEREDRLE_OBSOLETE46,
        // BAD_CALLING_ORDERRLE_OBSOLETE44,
        // FTP_USER_PASSWORD_INCORRECTRLE_OBSOLETE10,
        // FTP_CANT_RECONNECTRLE_OBSOLETE16,
        // FTP_COULDNT_GET_SIZERLE_OBSOLETE32,
        // FTP_COULDNT_SET_ASCIIRLE_OBSOLETE29,
        // FTP_WEIRD_USER_REPLYRLE_OBSOLETE12,
        // FTP_WRITE_ERRORRLE_OBSOLETE20,
        // LIBRARY_NOT_FOUNDRLE_OBSOLETE40,
        // MALFORMAT_USERRLE_OBSOLETE24,
        // SHARE_IN_USERLE_OBSOLETE57,
        // URL_MALFORMAT_USERRLE_NOT_BUILT_IN,
        // FTP_ACCESS_DENIEDRLE_REMOTE_ACCESS_DENIED,
        // FTP_COULDNT_SET_BINARYRLE_FTP_COULDNT_SET_TYPE,
        // FTP_QUOTE_ERRORRLE_QUOTE_ERROR,
        // TFTP_DISKFULLRLE_REMOTE_DISK_FULL,
        // TFTP_EXISTSRLE_REMOTE_FILE_EXISTS,
        // HTTP_RANGE_ERRORRLE_RANGE_ERROR,
        // FTP_SSL_FAILEDRLE_USE_SSL_FAILED,
        // OPERATION_TIMEOUTEDRLE_OPERATION_TIMEDOUT,
        // HTTP_NOT_FOUNDRLE_HTTP_RETURNED_ERROR,
        // HTTP_PORT_FAILEDRLE_INTERFACE_FAILED,
        // FTP_COULDNT_STOR_FILERLE_UPLOAD_FAILED,
        // FTP_PARTIAL_FILERLE_PARTIAL_FILE,
        // FTP_BAD_DOWNLOAD_RESUMERLE_BAD_DOWNLOAD_RESUME,
        // LDAP_INVALID_URLRLE_OBSOLETE62,
        // CONV_REQDRLE_OBSOLETE76,
        // CONV_FAILEDRLE_OBSOLETE75,
        // ALREADY_COMPLETEhelpers.promoteIntLiteral(c_int, 99999, .decimal),
    };

    pub fn errorFromEnum(val: CurlCodeEnum) CurlError!void {
        switch (val) {
            .ok => return,
            .unsupported_protocol => CurlError.UnsupportedProtocol,
            .failed_init => CurlError.FailedInit,
            .url_malformat => CurlError.UrlMalformat,
            .not_built_in => CurlError.NotBuiltIn,
            .couldnt_resolve_proxy => CurlError.CouldntResolveProxy,
            .couldnt_resolve_host => CurlError.CouldntResolveHost,
            .couldnt_connect => CurlError.CouldntConnect,
            .weird_server_reply => CurlError.WeirdServerReply,
            .remote_access_denied => CurlError.RemoteAccessDenied,
            .ftp_accept_failed => CurlError.FtpAcceptFailed,
            .ftp_weird_pass_reply => CurlError.FtpWeirdPassReply,
            .ftp_accept_timeout => CurlError.FtpAcceptTimeout,
            .ftp_weird_pasv_reply => CurlError.FtpWeirdPasvReply,
            .ftp_weird_227_format => CurlError.FtpWeird227Format,
            .ftp_cant_get_host => CurlError.FtpCantGetHost,
            .http2 => CurlError.Http2,
            .ftp_couldnt_set_type => CurlError.FtpCouldntSetType,
            .partial_file => CurlError.PartialFile,
            .ftp_couldnt_retr_file => CurlError.FtpCouldntRetrFile,
            .obsolete20 => CurlError.Obsolete20,
            .quote_error => CurlError.QuoteError,
            .http_returned_error => CurlError.HttpReturnedError,
            .write_error => CurlError.WriteError,
            .obsolete24 => CurlError.Obsolete24,
            .upload_failed => CurlError.UploadFailed,
            .read_error => CurlError.ReadError,
            .out_of_memory => CurlError.OutOfMemory,
            .operation_timedout => CurlError.OperationTimedout,
            .obsolete29 => CurlError.Obsolete29,
            .ftp_port_failed => CurlError.FtpPortFailed,
            .ftp_couldnt_use_rest => CurlError.FtpCouldntUseRest,
            .obsolete32 => CurlError.Obsolete32,
            .range_error => CurlError.RangeError,
            .obsolete34 => CurlError.Obsolete34,
            .ssl_connect_error => CurlError.SslConnectError,
            .bad_download_resume => CurlError.BadDownloadResume,
            .file_couldnt_read_file => CurlError.FileCouldntReadFile,
            .ldap_cannot_bind => CurlError.LdapCannotBind,
            .ldap_search_failed => CurlError.LdapSearchFailed,
            .obsolete40 => CurlError.Obsolete40,
            .obsolete41 => CurlError.Obsolete41,
            .aborted_by_callback => CurlError.AbortedByCallback,
            .bad_function_argument => CurlError.BadFunctionArgument,
            .obsolete44 => CurlError.Obsolete44,
            .interface_failed => CurlError.InterfaceFailed,
            .obsolete46 => CurlError.Obsolete46,
            .too_many_redirects => CurlError.TooManyRedirects,
            .unknown_option => CurlError.UnknownOption,
            .setopt_option_syntax => CurlError.SetoptOptionSyntax,
            .obsolete50 => CurlError.Obsolete50,
            .obsolete51 => CurlError.Obsolete51,
            .got_nothing => CurlError.GotNothing,
            .ssl_engine_notfound => CurlError.SslEngineNotfound,
            .ssl_engine_setfailed => CurlError.SslEngineSetfailed,
            .send_error => CurlError.SendError,
            .recv_error => CurlError.RecvError,
            .obsolete57 => CurlError.Obsolete57,
            .ssl_certproblem => CurlError.SslCertproblem,
            .ssl_cipher => CurlError.SslCipher,
            .peer_failed_verification => CurlError.PeerFailedVerification,
            .bad_content_encoding => CurlError.BadContentEncoding,
            .obsolete62 => CurlError.Obsolete62,
            .filesize_exceeded => CurlError.FilesizeExceeded,
            .use_ssl_failed => CurlError.UseSslFailed,
            .send_fail_rewind => CurlError.SendFailRewind,
            .ssl_engine_initfailed => CurlError.SslEngineInitfailed,
            .login_denied => CurlError.LoginDenied,
            .tftp_notfound => CurlError.TftpNotfound,
            .tftp_perm => CurlError.TftpPerm,
            .remote_disk_full => CurlError.RemoteDiskFull,
            .tftp_illegal => CurlError.TftpIllegal,
            .tftp_unknownid => CurlError.TftpUnknownid,
            .remote_file_exists => CurlError.RemoteFileExists,
            .tftp_nosuchuser => CurlError.TftpNosuchuser,
            .obsolete75 => CurlError.Obsolete75,
            .obsolete76 => CurlError.Obsolete76,
            .ssl_cacert_badfile => CurlError.SslCacertBadfile,
            .remote_file_not_found => CurlError.RemoteFileNotFound,
            .ssh => CurlError.Ssh,
            .ssl_shutdown_failed => CurlError.SslShutdownFailed,
            .again => CurlError.Again,
            .ssl_crl_badfile => CurlError.SslCrlBadfile,
            .ssl_issuer_error => CurlError.SslIssuerError,
            .ftp_pret_failed => CurlError.FtpPretFailed,
            .rtsp_cseq_error => CurlError.RtspCseqError,
            .rtsp_session_error => CurlError.RtspSessionError,
            .ftp_bad_file_list => CurlError.FtpBadFileList,
            .chunk_failed => CurlError.ChunkFailed,
            .no_connection_available => CurlError.NoConnectionAvailable,
            .ssl_pinnedpubkeynotmatch => CurlError.SslPinnedpubkeynotmatch,
            .ssl_invalidcertstatus => CurlError.SslInvalidcertstatus,
            .http2_stream => CurlError.Http2Stream,
            .recursive_api_call => CurlError.RecursiveApiCall,
            .auth_error => CurlError.AuthError,
            .http3 => CurlError.Http3,
            .quic_connect_error => CurlError.QuicConnectError,
            .proxy => CurlError.Proxy,
            .ssl_clientcert => CurlError.SslClientcert,
            .unrecoverable_poll => CurlError.UnrecoverablePoll,
            .too_large0 => CurlError.TooLarge,
            .ech_required1 => CurlError.EchRequired,
        }
    }
};
